# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.9
  heroku: circleci/heroku@1.2

jobs:
  test:
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn --frozen-lockfile && yarn run test:api
          name: Run YARN tests

workflows:
  heroku-deploy:
    jobs:
      - test
      - heroku/deploy-via-git:
          force: true
          requires:
            - test
          filters:
            branches:
              only: master
