# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.9
  heroku: circleci/heroku@1.2
  codecov: codecov/codecov@3.1.1

jobs:
  test:
    docker:
      - image: cimg/node:12.22.7
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test:api
          name: Run tests
      - codecov/upload:
          file: './coverage/apps/airbnb-clone-api/clover.xml'

workflows:
  test-branch:
    jobs:
      - test
  heroku-deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - main
      - heroku/deploy-via-git:
          force: true
          requires:
            - test
          filters:
            branches:
              only: main
